package mdsproject;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.event.ActionEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;

public class SecondWindow extends javax.swing.JFrame 
{
    String user1;
    String user2;
    
    DataBase myBD = new DataBase();
    /**
     * Creates new form SecondWindow
     */
    
    public SecondWindow(String user11) throws ClassNotFoundException, SQLException {
        user1 = user11;
        System.out.println(user1);
        initComponents();
        loadOnline();
        CurentDate();
        dynamic_time();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        timeText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MDSChat");
        setBounds(new java.awt.Rectangle(200, 200, 800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(750, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 80, 40));

        jButton2.setText("Send");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 80, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 630, 90));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Active users"));
        jPanel1.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 110, 350));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 590, 340));

        jButton3.setBackground(new java.awt.Color(0, 51, 204));
        jButton3.setPreferredSize(new java.awt.Dimension(33, 15));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton4.setBackground(new java.awt.Color(255, 102, 153));
        jButton4.setForeground(new java.awt.Color(255, 102, 204));
        jButton4.setPreferredSize(new java.awt.Dimension(33, 15));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton5.setBackground(new java.awt.Color(255, 255, 102));
        jButton5.setPreferredSize(new java.awt.Dimension(33, 15));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        jButton6.setBackground(new java.awt.Color(51, 255, 51));
        jButton6.setPreferredSize(new java.awt.Dimension(33, 15));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);

        jButton7.setBackground(new java.awt.Color(204, 0, 51));
        jButton7.setPreferredSize(new java.awt.Dimension(33, 15));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 630, 30));

        timeText.setBackground(new java.awt.Color(255, 204, 255));
        timeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeTextActionPerformed(evt);
            }
        });
        getContentPane().add(timeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String toSendMessage = jTextArea1.getText();
        
        try {
            //System.out.println(toSendMessage);
            myBD.sendMessage(user1, user2, toSendMessage);
            String listaMesaje = myBD.getMessages(user1, user2);
            jTextArea2.setText("");
            jTextArea2.replaceSelection(listaMesaje);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SecondWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SecondWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String listaMesaje = myBD.getMessages(user1, user2);
            jTextArea2.setText("");
            jTextArea2.replaceSelection(listaMesaje);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SecondWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SecondWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.getContentPane().setBackground(Color.blue);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.getContentPane().setBackground(Color.pink);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       this.getContentPane().setBackground(Color.yellow);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.getContentPane().setBackground(Color.green);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       this.getContentPane().setBackground(Color.red);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void timeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeTextActionPerformed

    public void loadOnline() throws ClassNotFoundException, SQLException
    {
        ArrayList <String> myVector;
        myVector = myBD.getUsers("plm");
        
        for(int i = 0; i < myVector.size(); i++)
        {
            GridBagConstraints constraints = new GridBagConstraints();
            JButton button = new JButton(myVector.get(i));
            constraints.gridx=0;
            constraints.gridy=i;
            button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) 
            {buttonActionPerformed(evt);}
            
            private void buttonActionPerformed(ActionEvent evt) {
                user2 = button.getText();
                System.out.println(user1+" "+user2);
                }
            });
            jPanel1.add(button, constraints);
            jPanel1.repaint();
        }
        
    }
   
    
      public void CurentDate()
    {
        Calendar cal= new GregorianCalendar();
        int sec = cal.get(Calendar.SECOND);
        int min = cal.get(Calendar.MINUTE);
        int ore = cal.get(Calendar.HOUR);
        timeText.setText("Time: "+ore+":"+min+":"+sec);
    }
    
    public void dynamic_time()
    {
        Thread ceas=new Thread(){
            public void run(){
                for(;;){
                   Calendar cal= new GregorianCalendar();
        int sec = cal.get(Calendar.SECOND);
        int min = cal.get(Calendar.MINUTE);
        int ore = cal.get(Calendar.HOUR);
        timeText.setText("Time: "+ore+":"+min+":"+sec); 
        
                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(SecondWindow.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
        ceas.start();
    }
    //aici
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField timeText;
    // End of variables declaration//GEN-END:variables
}
